services:
  challenge-migration:
    container_name: challenger
    image: challenger:latest
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080/tcp
    restart: always